name: MSBuild

on:
  push:
    branches: [ "main" ]
    paths-ignore:
     - LICENSE
     - README.md
#  pull_request:
#    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: read
  actions: write

jobs:
  building-debug-x86:
    name: Building Debug (x86)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: dotnet restore ${{env.SOLUTION_FILE_PATH}}

      - name: Building Debug (x86)
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=Debug /p:Platform=x86 ${{env.SOLUTION_FILE_PATH}}

      - name: Uploading build
        uses: actions/upload-artifact@v4
        with:
          name: BuildDebug32
          path: |
            ${{env.SOLUTION_FILE_PATH}}\build\**\*.exe
            ${{env.SOLUTION_FILE_PATH}}\build\**\*.pdb
          if-no-files-found: error

  building-debug-x86-64:
    name: Building Debug (x86_64)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: dotnet restore ${{env.SOLUTION_FILE_PATH}}

      - name: Building Debug (x86_64)
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=Debug /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

      - name: Uploading build
        uses: actions/upload-artifact@v4
        with:
          name: BuildDebug64
          path: |
            ${{env.SOLUTION_FILE_PATH}}\build\**\*.exe
            ${{env.SOLUTION_FILE_PATH}}\build\**\*.pdb
          if-no-files-found: error

  building-release-x86:
    name: Building Release (x86)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: dotnet restore ${{env.SOLUTION_FILE_PATH}}

      - name: Building Release (x86)
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=Release /p:Platform=x86 ${{env.SOLUTION_FILE_PATH}}

      - name: Uploading build
        uses: actions/upload-artifact@v4
        with:
          name: BuildRelease32
          path: |
            ${{env.SOLUTION_FILE_PATH}}\build\**\*.exe
            ${{env.SOLUTION_FILE_PATH}}\build\**\*.pdb
          if-no-files-found: error

  building-release-x86-64:
    name: Building Release (x86_64)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: dotnet restore ${{env.SOLUTION_FILE_PATH}}

      - name: Building Release (x86_64)
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=Release /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

      - name: Uploading build
        uses: actions/upload-artifact@v4
        with:
          name: BuildRelease64
          path: |
            ${{env.SOLUTION_FILE_PATH}}\build\**\*.exe
            ${{env.SOLUTION_FILE_PATH}}\build\**\*.pdb
          if-no-files-found: error

  testing-debug-x86:
    name: Testing Debug (x86)
    runs-on: windows-latest
    needs: building-debug-x86

    steps:
      - name: Downloading Debug (x86)
        uses: actions/download-artifact@v4
        with:
          name: BuildDebug32
          path: |
            ${{env.SOLUTION_FILE_PATH}}\build

      - name: Testing Debug (x86)
        timeout-minutes: 3
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ${{env.SOLUTION_FILE_PATH}}\build\x86\Debug\Detours.exe

  testing-debug-x86-64:
    name: Testing Debug (x86_64)
    runs-on: windows-latest
    needs: building-debug-x86-64

    steps:
      - name: Downloading Debug (x86_64)
        uses: actions/download-artifact@v4
        with:
          name: BuildDebug64
          path: |
            ${{env.SOLUTION_FILE_PATH}}\build

      - name: Testing Debug (x86_64)
        timeout-minutes: 3
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ${{env.SOLUTION_FILE_PATH}}\build\x86_64\Debug\Detours.exe

  testing-release-x86:
    name: Testing Release (x86)
    runs-on: windows-latest
    needs: building-release-x86

    steps:
      - name: Downloading Release (x86)
        uses: actions/download-artifact@v4
        with:
          name: BuildRelease32
          path: |
            ${{env.SOLUTION_FILE_PATH}}\build

      - name: Testing Release (x86)
        timeout-minutes: 3
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ${{env.SOLUTION_FILE_PATH}}\build\x86\Release\Detours.exe

  testing-release-x86-64:
    name: Testing Release (x86_64)
    runs-on: windows-latest
    needs: building-release-x86-64

    steps:
      - name: Downloading Release (x86_64)
        uses: actions/download-artifact@v4
        with:
          name: BuildRelease64
          path: |
            ${{env.SOLUTION_FILE_PATH}}\build

      - name: Testing Release (x86_64)
        timeout-minutes: 3
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ${{env.SOLUTION_FILE_PATH}}\build\x86_64\Release\Detours.exe
